<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogLevelTwoSeeder extends Seeder
{
    public $data = [
        // Мясная продукция
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/beef/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/beautiful-cow-on-green-grass-with-blue-sky_11244791.htm#query=cow&position=14&from_view=search&track=sph">Изображение от vwalakte</a> на Freepik',
            'link' => 'beef',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Говядина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/chicken/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/closeup-shot-of-a-white-hen-walking-in-a-field_10759817.htm#query=%D0%9A%D1%83%D1%80%D0%B8%D1%86%D0%B0&position=27&from_view=search&track=sph">Изображение от wirestock</a> на Freepik',
            'link' => 'chicken',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Курица',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/turkey/1.jpeg',
            'image_licence_link' => 'Изображение от <a href="https://ru.freepik.com/free-photo/side-view-turkey-outdoors_8775118.htm#page=2&query=%D0%98%D0%BD%D0%B4%D0%B5%D0%B9%D0%BA%D0%B0&position=30&from_view=search&track=sph">Freepik</a>',
            'link' => 'turkey',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Индейка',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/pork/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/closeup-shot-of-three-domesticated-pigs_17244243.htm#query=pig&position=37&from_view=search&track=sph">Изображение от wirestock</a> на Freepik',
            'link' => 'pork',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Свинина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/sheep/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/head-of-a-white-sheep_15672323.htm#query=sheep&position=4&from_view=search&track=sph">Изображение от wirestock</a> на Freepik',
            'link' => 'sheep',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Баранина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/rabbit/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/portrait-of-a-cute-fluffy-gray-rabbit-with-ears-on-a-natural-green_9604087.htm#page=2&query=rabbit&position=47&from_view=search&track=sph">Изображение от pereslavtseva</a> на Freepik',
            'link' => 'rabbit',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Крольчатина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/goat/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/brown-and-white-mother-and-baby-goats-inside-a-barn_12045833.htm#query=goat&position=1&from_view=search&track=sph">Изображение от wirestock</a> на Freepik',
            'link' => 'goat',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Козлятина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/horse/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/horse-alezan-brown-ride-mane_1102300.htm#query=horse&position=42&from_view=search&track=sph">Изображение от senivpetro</a> на Freepik',
            'link' => 'horse',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Конина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/bear/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/close-wild-big-brown-bear-near-a-forest-lake_11011847.htm#query=bear&position=29&from_view=search&track=sph">Изображение от byrdyak</a> на Freepik',
            'link' => 'bear',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Медвежатина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/deer/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/red-deer-in-the-nature-habitat-during-the-deer-rut-european-wildlife_16755911.htm#query=deer&position=34&from_view=search&track=sph">Изображение от vladimircech</a> на Freepik',
            'link' => 'deer',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Оленина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/moose/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/beautiful-shot-of-a-moose-or-elk-on-a-road-near-the-woods_14376060.htm#page=3&query=moose&position=45&from_view=search&track=sph">Изображение от wirestock</a> на Freepik',
            'link' => 'moose',
            'order' => 1,
            'catalog_level_one_id' => 1,
            'title' => 'Лосятина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/meat/images/main/sub/other/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/wild-boar-in-the-nature-habitat-dangerous-animal-in-the-forest-czech-republic-nature-sus-scrofa_16206151.htm#query=%D0%BA%D0%B0%D0%B1%D0%B0%D0%BD&position=2&from_view=search&track=sph">Изображение от vladimircech</a> на Freepik',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 1,
            'title' => 'Остальное',
        ],











        //   Рыба
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/trout/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/two-raw-seabass-with-spices_7121185.htm#page=2&query=%D1%84%D0%BE%D1%80%D0%B5%D0%BB%D1%8C&position=0&from_view=search&track=sph">Изображение от timolina</a> на Freepik',
            'link' => 'trout',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Форель',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/pollock/1.jpeg',
            'image_licence_link' => 'Изображение от <a href="https://ru.freepik.com/free-photo/composition-with-frozen-fish-on-the-table_14278035.htm#query=%D0%9C%D0%B8%D0%BD%D1%82%D0%B0%D0%B9&position=0&from_view=search&track=sph">Freepik</a>',
            'link' => 'pollock',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Минтай',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/salmon_fish/1.jpeg',
            'image_licence_link' => 'Изображение от <a href="https://ru.freepik.com/free-photo/slices-of-raw-red-salmon_9659716.htm#query=%D0%A1%D0%B5%D0%BC%D0%B3%D0%B0&position=3&from_view=search&track=sph">Freepik</a>',
            'link' => 'salmon_fish',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Семга',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/pike/1.jpeg',
            'image_licence_link' => 'Изображение от <a href="https://ru.freepik.com/free-photo/close-up-of-fresh-pike-fish_3105527.htm#query=%D0%A9%D1%83%D0%BA%D0%B0&position=27&from_view=search&track=sph">Freepik</a>',
            'link' => 'pike',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Щука',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/crucian_carp/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/fresh-raw-crucian-on-a-wooden-with-herbs_6963638.htm#query=%D0%9A%D0%B0%D1%80%D0%B0%D1%81%D1%8C&position=2&from_view=search&track=sph">Изображение от timolina</a> на Freepik',
            'link' => 'crucian_carp',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Карась',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/flounder/1.jpeg',
            'image_licence_link' => 'Photo by <a href="https://unsplash.com/@brian_yuri?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Brian Yurasits</a> on <a href="https://unsplash.com/photos/KhTywORJC74?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
            'link' => 'flounder',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Камбала',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/cod/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/bottom-view-fish-fry-fried-eggplants-onion-peppers-on-wood-board-spices-in-small-bowls-fork-and-knife-tomatoes-oil-bottle-mint-dill-on-dark-background_16607684.htm#query=%D0%A2%D1%80%D0%B5%D1%81%D0%BA%D0%B0&position=30&from_view=search&track=sph">Изображение от KamranAydinov</a> на Freepik',
            'link' => 'cod',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Треска',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/carp/1.jpeg',
            'image_licence_link' => '<a href="https://ru.freepik.com/free-photo/fried-fish-carp-and-fresh-vegetable-salad-flat-lay-top-view_7688790.htm#page=2&query=%D0%9A%D0%B0%D1%80%D0%BF&position=35&from_view=search&track=sph">Изображение от timolina</a> на Freepik',
            'link' => 'carp',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Карп',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/pink_salmon/1.jpeg',
            'image_licence_link' => '',
            'link' => 'pink_salmon',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Горбуша',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/sardine/1.jpeg',
            'image_licence_link' => '',
            'link' => 'sardine',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Сардина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/herring/1.jpeg',
            'image_licence_link' => '',
            'link' => 'herring',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Сельдь',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/mackerel/1.jpeg',
            'image_licence_link' => '',
            'link' => 'mackerel',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Скумбрия',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/tuna/1.jpeg',
            'image_licence_link' => '',
            'link' => 'tuna',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Тунец',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/octopus/1.jpeg',
            'image_licence_link' => '',
            'link' => 'octopus',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Осьминог',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/tilapia/1.jpeg',
            'image_licence_link' => '',
            'link' => 'tilapia',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Тилапия',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/pangasius/1.jpeg',
            'image_licence_link' => '',
            'link' => 'pangasius',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Пангасиус',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/shrimp/1.jpeg',
            'image_licence_link' => '',
            'link' => 'shrimp',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Креветка',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/squid/1.jpeg',
            'image_licence_link' => '',
            'link' => 'squid',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Кальмар',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/perch/1.jpeg',
            'image_licence_link' => '',
            'link' => 'perch',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Окунь',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/crab/1.jpeg',
            'image_licence_link' => '',
            'link' => 'crab',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Краб',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/crayfish/1.jpeg',
            'image_licence_link' => '',
            'link' => 'crayfish',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Рак',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/keta/1.jpeg',
            'image_licence_link' => '',
            'link' => 'keta',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Кета',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/sea_bass/1.jpeg',
            'image_licence_link' => '',
            'link' => 'sea_bass',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Сибас',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/saira/1.jpeg',
            'image_licence_link' => '',
            'link' => 'saira',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Сайра',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/sprat/1.jpeg',
            'image_licence_link' => '',
            'link' => 'sprat',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Килька',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/anchovy/1.jpeg',
            'image_licence_link' => '',
            'link' => 'anchovy',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Анчоус',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/sardine/1.jpeg',
            'image_licence_link' => '',
            'link' => 'sardine',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Сардина',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/burbot/1.jpeg',
            'image_licence_link' => '',
            'link' => 'burbot',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Налим',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/vobla/1.jpeg',
            'image_licence_link' => '',
            'link' => 'vobla',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Вобла',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/sturgeon/1.jpeg',
            'image_licence_link' => '',
            'link' => 'sturgeon',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Осетр',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/mussels/1.jpeg',
            'image_licence_link' => '',
            'link' => 'mussels',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Мидии',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/turbot/1.jpeg',
            'image_licence_link' => '',
            'link' => 'turbot',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Палтус',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/bream/1.jpeg',
            'image_licence_link' => '',
            'link' => 'bream',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Лещ',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/catfish/1.jpeg',
            'image_licence_link' => '',
            'link' => 'catfish',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Сом',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/zander/1.jpeg',
            'image_licence_link' => '',
            'link' => 'zander',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Судак',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/omul/1.jpeg',
            'image_licence_link' => '',
            'link' => 'omul',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Омуль',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/roach/1.jpeg',
            'image_licence_link' => '',
            'link' => 'roach',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Плотва',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/capelin/1.jpeg',
            'image_licence_link' => '',
            'link' => 'capelin',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Мойва',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/salmon/1.jpeg',
            'image_licence_link' => '',
            'link' => 'salmon',
            'order' => 1,
            'catalog_level_one_id' => 2,
            'title' => 'Лосось',
        ],
        [
            'image' => 'public/catalog/levelOne/items/fish/images/main/sub/other/1.jpeg',
            'image_licence_link' => 'Изображение от <a href="https://ru.freepik.com/free-photo/top-view-mix-of-fresh-fishes-on-ice_5567771.htm#page=2&query=%D0%9A%D0%B0%D1%80%D0%BF&position=22&from_view=search&track=sph">Freepik</a>',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 2,
            'title' => 'Остальное',
        ],












        // Молочная продукция
        [
            'image' => 'public/catalog/levelTwo/items/3/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'milk',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Молоко',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'milk_сream',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Сливки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'kefir',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Кефир',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'koumiss',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Кумыс',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'butter',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Масло',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'margarine',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Маргарин',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'сottage_cheese',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Творог',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'sour_cream',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Сметана',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'ryazhenka',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Ряженка',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'milkshake',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Молочные коктели',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'yogurt',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Йогурт',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'curds',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Творожные сырки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'pudding',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Пудинг',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'сondensed_milk',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Сгущенное молоко',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/4/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'cheese',
            'order' => 1,
            'catalog_level_one_id' => 3,
            'title' => 'Сыр',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 3,
            'title' => 'Остальное',
        ],









        // Яйца
        [
            'image' => 'public/catalog/levelTwo/items/5/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'chicken-eggs',
            'order' => 1,
            'catalog_level_one_id' => 4,
            'title' => 'Куринные яйца',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'quail',
            'order' => 1,
            'catalog_level_one_id' => 4,
            'title' => 'Перепелинные яйца',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 4,
            'title' => 'Остальное',
        ],




        // Фрукты
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'apple',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Яблоки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'pears',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Груши',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Мандарины',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Апельсины',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Бананы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Манго',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Виноград',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Слива',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Хурма',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Айва',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Киви',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Грейпфрут',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Гранат',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Лимон',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Персики',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Кокос',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Авокадо',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Хурма',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Арбуз',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 5,
            'title' => 'Дыня',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 5,
            'title' => 'Остальное',
        ],









        // Овощи
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Картофель',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Помидоры',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Огурцы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Капуста',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Лук репчатый',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Лук пырей',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Салат',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Петрушка',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Укроп',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Баклажан',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Тыква',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Кабачок',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Перец',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Свекла',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Морковь',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Чеснок',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Редиска',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Редька',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 6,
            'title' => 'Кукуруза',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 6,
            'title' => 'Остальное',
        ],








        // Ягода
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Голубика',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Клубника',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Черемуха',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Черноплодная рябина',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Рябина',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Жимолость',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Смородина',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Крыжовник',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Земляника',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Облепиха',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Клюква',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Брусника',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Ежевика',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Боярышник',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Инжир',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Черешня',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Вишня',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Шелковица',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Ирга',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 7,
            'title' => 'Личи',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 7,
            'title' => 'Остальное',
        ],






        // Хлеб
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Хлеб пшеничный',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Хлеб ржаной',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Лаваш, лепешки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Пирожки сладкие',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Пироги сладкие',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Пирожки сытные',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Пироги сытные',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Булочки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Батон',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Хлебцы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 8,
            'title' => 'Сушки и сухарики',
        ],








        // Кондитерские изделия
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Торты',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Пирожные',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Кексы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Пряники',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Конфеты',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Карамель',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Зефир',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Шоколад',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Пастила',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Восточные сладости',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Печенье',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Круассаны',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Вафли',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 9,
            'title' => 'Бисквитные изделия',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 9,
            'title' => 'Остальное',
        ],



        // Чай
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 10,
            'title' => 'Черный чай',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 10,
            'title' => 'Зеленый чай',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 10,
            'title' => 'Травы, листья и сборы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 10,
            'title' => 'Остальное',
        ],






        // Мед
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 11,
            'title' => 'Мед',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'perga',
            'order' => 1,
            'catalog_level_one_id' => 11,
            'title' => 'Перга',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'propolis',
            'order' => 1,
            'catalog_level_one_id' => 11,
            'title' => 'Прополис',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'Pollen',
            'order' => 1,
            'catalog_level_one_id' => 11,
            'title' => 'Пыльца',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'milk',
            'order' => 1,
            'catalog_level_one_id' => 11,
            'title' => 'Маточное молочко',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'wax',
            'order' => 1,
            'catalog_level_one_id' => 11,
            'title' => 'Воск',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 11,
            'title' => 'Остальное',
        ],







        // Бакалея
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'buckwheat',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Гречневая крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'oatmeal',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Овсянная крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Рис',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Пшено',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Булгур',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Кускус',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Кукурузная крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Манная крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Перловая крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Ячневая крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Чечевичная крупа',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Фасоль',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Горох',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Соль',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Сахар',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Растительные масла',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Макароны, лапша',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Мука',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Дрожжи',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 12,
            'title' => 'Тесто',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 12,
            'title' => 'Остальное',
        ],










        // Орехи
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Грецкий орех',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Арахис',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Изюм',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Сухофрукты',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Семечки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Кешью',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Миндаль',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Курага',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Фундук',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Кедровый орех',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Чернослив',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 13,
            'title' => 'Фисташки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 13,
            'title' => 'Остальное',
        ],







        // Консервы
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 14,
            'title' => 'Консервированные овощи',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 14,
            'title' => 'Консервированные грибы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 14,
            'title' => 'Консервированные фрукты',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 14,
            'title' => 'Мясные консервы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 14,
            'title' => 'Рыбные консервы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 14,
            'title' => 'Варенье',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 14,
            'title' => 'Остальное',
        ],








        // Грибы
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Шампиньоны',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Вешенка',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Опята',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Лисички',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Подберезовики',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Подосиновики',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Белые',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Маслята',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 15,
            'title' => 'Моховик',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 15,
            'title' => 'Остальное',
        ],









        // Вода
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 16,
            'title' => 'Минеральная вода',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 16,
            'title' => 'Сок',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 16,
            'title' => 'Квас',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 16,
            'title' => 'Остальное',
        ],








        // Цветы
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Тюльпан',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Ирис',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Гербера',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Альстромерия',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Хризантема',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Пион',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Ромашка',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Гвоздика',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Лилия',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Роза',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Гипсофила',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Эустома',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Гиацинт',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Гортензия',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Лютик',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Мимоза',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Хризантема',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Сирень',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Орхидея',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Верба',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 17,
            'title' => 'Букеты',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 17,
            'title' => 'Остальное',
        ],





        // Семена
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена овощей',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена фруктов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена ягод',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена орехов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена домашних цветов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена плодовых деревьев',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена неплодовых деревьев',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена плодовых растений',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена декоративных растений',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена многолетних цветов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 18,
            'title' => 'Семена однолетних цветов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 18,
            'title' => 'Остальное',
        ],








        // Саженцы
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы овощей',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы фруктов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы ягод',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы орехов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы домашних цветов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы плодовых деревьев',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы неплодовых деревьев',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы плодовых растений',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы декоративных растений',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы многолетних цветов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 19,
            'title' => 'Саженцы однолетних цветов',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 19,
            'title' => 'Остальное',
        ],






        // Растения
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 20,
            'title' => 'Комнатные',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 20,
            'title' => 'Декоративные',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/6/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 20,
            'title' => 'Садовые',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 20,
            'title' => 'Остальное',
        ],







        // Животноводство
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'beef',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Коровы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'chicken',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Курицы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'turkey',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Индейки',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'pork',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Свиньи',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'sheep',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Овцы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'rabbit',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Кролики',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'goat',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Козлы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'moose',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Пушные животные',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/2/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'fish',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Рыба',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'beef',
            'order' => 1,
            'catalog_level_one_id' => 21,
            'title' => 'Пчелы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 21,
            'title' => 'Остальное',
        ],









        // Дрова, сено, удобрения
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 22,
            'title' => 'Дрова',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 22,
            'title' => 'Сено',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 22,
            'title' => 'Навоз',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 22,
            'title' => 'Кругляк',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 22,
            'title' => 'Пиломатериалы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 22,
            'title' => 'Остальное',
        ],







        // Эко туризм
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 23,
            'title' => 'Эко туризм',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 23,
            'title' => 'Остальное',
        ],





        // Одежда
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 24,
            'title' => 'Национальные головные уборы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 24,
            'title' => 'Национальная одежда',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 24,
            'title' => 'Национальная обувь',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 24,
            'title' => 'Национальные костюмы',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/1/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => '',
            'order' => 1,
            'catalog_level_one_id' => 24,
            'title' => 'Национальные сувениры',
        ],
        [
            'image' => 'public/catalog/levelTwo/items/0/images/main/1.jpg',
            'image_licence_link' => '',
            'link' => 'other',
            'order' => 999,
            'catalog_level_one_id' => 24,
            'title' => 'Остальное',
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->data as $dataItem) {
            DB::table('catalog_level_two')->insert($dataItem);
        }
    }
}
