<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OfferSeeder extends Seeder
{
    public $data = [
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '50.507574',
            'map_marker_lng' => '80.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '51.507574',
            'map_marker_lng' => '81.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '52.507574',
            'map_marker_lng' => '82.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '53.507574',
            'map_marker_lng' => '83.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '54.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '55.507574',
            'map_marker_lng' => '85.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '86.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '57.507574',
            'map_marker_lng' => '87.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '58.507574',
            'map_marker_lng' => '88.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '59.507574',
            'map_marker_lng' => '89.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '60.507574',
            'map_marker_lng' => '90.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '61.507574',
            'map_marker_lng' => '91.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '62.507574',
            'map_marker_lng' => '92.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '63.507574',
            'map_marker_lng' => '93.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '64.507574',
            'map_marker_lng' => '94.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '65.507574',
            'map_marker_lng' => '95.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '66.507574',
            'map_marker_lng' => '96.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '66.527574',
            'map_marker_lng' => '96.929882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '66.587574',
            'map_marker_lng' => '96.959882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '66.577574',
            'map_marker_lng' => '96.949882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №1 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №1 Говядина Томск',
            'is_active' => true,
            'is_approved' => 1,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 100,
            'price_description' => 'test price_description 100',
            'region_id' => 1,
            'title' => 'Предложение №1 Говядина Томск',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение №2 Молоко ТО',
            'catalog_level_one_id' => 2,
            'catalog_level_two_id' => 3,
            'country_id' => 1,
            'description' => 'Описание Предложение №2 Молоко ТО',
            'is_active' => true,
            'is_approved' => 0,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939582',
            'measure_id' => 2,
            'order' => 1,
            'organization_id' => 2,
            'phone' => '+7 111 111 11 12',
            'photo_1' => 'public/users/1/offer/2/photo/1.jpg',
            'price' => 200,
            'region_id' => 1,
            'title' => 'Предложение №2 Молоко ТО',
            'user_id' => 1,
        ],
        [
            'address' => 'адрес Предложение Говядина №3 Томск',
            'description' => 'Описание Предложение №3 Говядина Томск',
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'city_id' => 1,
            'country_id' => 1,
            'is_active' => true,
            'is_approved' => 0,
            'measure_id' => 4,
            'order' => 1,
            'organization_id' => 3,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/2/offer/1/photo/1.jpg',
            'price' => 200,
            'price_description' => 'test price_description 200',
            'region_id' => 1,
            'title' => 'Предложение №3 Говядина Томск',
            'user_id' => 2,
        ],
        [
            'address' => 'адрес Предложение №4 Курица Новосибирск',
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 2,
            'city_id' => 4,
            'country_id' => 1,
            'description' => 'Описание Предложение №4 Курица Новосибирск',
            'is_active' => true,
            'is_approved' => 0,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939182',
            'measure_id' => 4,
            'order' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/2/offer/2/photo/1.jpg',
            'photo_2' => 'public/users/2/offer/2/photo/2.jpg',
            'price' => 100,
            'region_id' => 2,
            'title' => 'Предложение №4 Курица Новосибирск',
            'user_id' => 2,
        ],
        [
            'address' => 'адрес Предложение №111 Говядина Томск',
            'city_id' => 1,
            'catalog_level_one_id' => 1,
            'catalog_level_two_id' => 1,
            'country_id' => 1,
            'description' => 'Описание Предложение №111 Говядина Томск',
            'is_active' => true,
            'is_approved' => false,
            'map_marker_lat' => '56.507574',
            'map_marker_lng' => '84.939882',
            'measure_id' => 1,
            'order' => 1,
            'organization_id' => 1,
            'phone' => '+7 111 111 11 11',
            'photo_1' => 'public/users/1/offer/1/photo/1.jpg',
            'photo_2' => 'public/users/1/offer/1/photo/2.jpg',
            'photo_3' => 'public/users/1/offer/1/photo/3.jpg',
            'price' => 1000,
            'price_description' => 'test price_description 1000',
            'region_id' => 1,
            'title' => 'Предложение №111 Говядина Томск',
            'user_id' => 1,
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->data as $dataItem) {
            DB::table('offer')->insert($dataItem);
        }
    }
}
