import 'views/pages/auth/login';
import 'views/pages/auth/register';
import 'views/pages/catalog/secondLevel';
import 'views/pages/home';
import 'views/pages/offers';
import 'views/pages/offers/item';
import 'views/pages/profile/offers';
import 'views/pages/profile/organization-info';
import 'views/pages/profile/personal-info';
