import 'views/components/form/error';
import 'views/components/inputs/file/item';
import 'views/components/inputs/form';
import 'views/components/map/2gis/components/add-marker';
import 'views/modules/pages/profile/common/body/create';
import 'views/modules/pages/profile/common/container/file-field';
import 'views/modules/pages/profile/common/container/form-field';
import 'views/modules/pages/profile/common/container/section';
import 'views/modules/pages/profile/common/footer';
